# PlayerLevels Configuration
# Version 1.0.0

settings:
  enable-plugin: true

  levels:
    base-xp: 100       # Base XP required for level 1
    xp-multiplier: 1.5 # XP increase per level (exponential scaling)

  statistics:
    1:
      statistic: "MINE_BLOCK"
      material: "STONE"
      xp-value: 5      # Gain 5 XP per stone mined
    2:
      statistic: "MINE_BLOCK"
      material: "DIAMOND_ORE"
      xp-value: 50     # Gain 50 XP per diamond ore mined
    3:
      statistic: "KILL_ENTITY"
      entity: "ZOMBIE"
      xp-value: 20     # Gain 20 XP per zombie killed
    4:
      statistic: "KILL_ENTITY"
      entity: "ENDER_DRAGON"
      xp-value: 500    # Gain 500 XP per Ender Dragon killed
    5:
      statistic: "PLAY_ONE_MINUTE"
      xp-value: 0.05   # Gain 0.05 XP per minute played (3 XP per hour)
    6:
      statistic: "DEATHS"
      xp-value: -50    # Lose 50 XP per death
    7:
      statistic: "JUMP"
      xp-value: 0.1    # Gain 0.1 XP per jump
    8:
      statistic: "WALK_ONE_CM"
      xp-value: 0.001  # Gain 0.001 XP per cm walked (1 XP per 10 blocks)
    9:
      statistic: "DAMAGE_DEALT"
      xp-value: 0.05   # Gain 0.05 XP per damage point dealt
    10:
      statistic: "CHEST_OPENED"
      xp-value: 1      # Gain 1 XP per chest opened

  rewards:
    5:
      commands:
        - "give %player% diamond 1"
      message: "&aYou reached Level 5! Enjoy a diamond!"
    10:
      commands:
        - "give %player% diamond 5"
        - "eco give %player% 1000"
      message: "&eLevel 10! You got 5 diamonds and $1,000!"
    25:
      commands:
        - "give %player% diamond_sword 1"
        - "eco give %player% 5000"
      message: "&6Congratulations on Level 25! You've earned a diamond sword and $5,000!"
    50:
      commands:
        - "give %player% diamond_block 5"
        - "eco give %player% 10000"
      message: "&d&lLevel 50! Incredible achievement! Here's 5 diamond blocks and $10,000!"
    100:
      commands:
        - "give %player% netherite_ingot 5"
        - "eco give %player% 50000"
        - "lp user %player% permission set essentials.fly true"
      message: "&c&lLEVEL 100! &6&lYou are truly a master! Enjoy netherite, money, and the ability to fly!"

storage:
  type: "sqlite"  # "sqlite" or "mysql"

  # MySQL connection settings (only used if type is "mysql")
  mysql:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""

# Messages
messages:
  prefix: "&8[&6PlayerLevels&8] "
  level-up: "&aYou've reached level %level%!"